title: Deipss' blog
description: powered by just-the-docs
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Deipss : https://github.com/deipss

mermaid:
    # Version of mermaid library
    # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
    version: "9.1.3"


